version: '3'
services:
  spring-backend:
    container_name: spring-backend
    build:
      context: ./backend
    image: spring-backend
    ports:
    - "8080:8080"
    volumes:
    - ./logs:/usr/local/logs/
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    depends_on: [ zookeeper ]
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /Users/xichuang.chen/soft/docker/image-dir:/etc/mirro

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      #    - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html
    command: /bin/bash -c "nginx -g 'daemon off;'"