spring:
  application:
    name: kafkademo
  kafka:
    bootstrap-servers: kafka:9092
    #-------------producer
    producer:
      retries: 0
      buffer-memory: 40960
      batch-size: 4096
      #指定消息key和消息体的编解码方式
      # key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # value-serializer: org.apache.kafka.common.serialization.StringSerializer
    #-------------producer
    consumer:
      group-id: consume-test
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 100
      #  key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      # value-deserializer: org.apache.kafka.common.serialization.StringSerializer
server:
  port: 8088
